# Generated by Django 6.1.1 on 2026-10-04 07:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("kind", models.CharField(blank=True, max_length=16)),
                ("file", models.FileField(blank=True, null=True, upload_to="reports/")),
                ("file_deleted", models.BooleanField(default=False)),
                ("language", models.CharField(default="en", max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("needs_confirmation", "Needs Confirmation"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="failed",
                        max_length=24,
                    ),
                ),
                ("extraction", models.JSONField(blank=True, default=dict)),
                ("analysis", models.JSONField(blank=True, default=dict)),
                ("reasons", models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
